# Generated by Django 4.2.2 on 2023-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('EL', 'EL'), ('casual', 'CL(First Half)'), ('casual', 'CL(Second Half)'), ('casual', 'CL(Full Day)'), ('emergency', 'Medical Leave'), ('compensatory', 'Compensatory Leave'), ('summer', 'Summer Break'), ('winter', 'Winter Break')], default='EL', max_length=25, null=True),
        ),
    ]
