# Generated by Django 4.2 on 2023-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200904_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dateissued',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeid',
        ),
        migrations.AddField(
            model_name='employee',
            name='employeecode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Employee Code Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Profile Image (optional)'),
        ),
    ]
