# Generated by Django 4.2.2 on 2023-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_dateissued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Visiting', 'Visiting'), ('Contract', 'Contract')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type'),
        ),
    ]
